<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE>
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title>跳转路劲与页面清单</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<style type="text/css">
		table{ border-collapse:collapse; font-family:"黑体"; font-size:14px;}
		tr{ line-height:30px;}
		td{ padding-left:15px; border:#999999 1px solid;}
	</style>

  </head>
  
  <body>
    	<div style="width:1000px; margin:0 auto; margin-top:20px;">
			<table width="100%" border="0">
			  <tr style="font-weight:bold;">
				<td width="8%">序号</td>
				<td width="20%">页面名称</td>
				<td width="34%">请求URL</td>
				<td width="30%">对应页面</td>
				<td width="8%">负责人</td>
			  </tr>
			 <tr>
				<td>1</td>
				<td>我的动态</td>
				<td>anzhitrend/findAnzhiTrendMySelf.do</td>
				<td>home_page_my_activity.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>2</td>
				<td>好友动态</td>
				<td>anzhitrend/findAnzhiTrendMySelf.do</td>
				<td>index/home_page_friend_activity.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>3</td>
				<td>好友管理</td>
				<td>anzhifriend/findMyFriendAll.do</td>
				<td>home_page_friend_manage.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>4</td>
				<td>基本信息(读者)</td>
				<td>&nbsp;</td>
				<td>my_infomation_basic.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>5</td>
				<td>头像管理</td>
				<td>anzhiheadimguserecord/findAnzhiHeadImgUseRecordMySelf.do</td>
				<td>my_infomation_head_img.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>6</td>
				<td>个人资料</td>
				<td></td>
				<td>my_infomation_my_info.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>7</td>
				<td>个性设置</td>
				<td>&nbsp;</td>
				<td>my_infomation_person_set.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>8</td>
				<td>实名认证</td>
				<td>&nbsp;</td>
				<td>my_infomation_realname.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>9</td>
				<td>修改密码</td>
				<td>&nbsp;</td>
				<td>writer_info_upd_pass.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>10</td>
				<td>注册</td>
				<td>anzhimember/addAnzhiMember.do</td>
				<td>index.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>11</td>
				<td>作者专区(读者)</td>
				<td>&nbsp;</td>
				<td>author_apply.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>12</td>
				<td>作者专区(作者)</td>
				<td>&nbsp;</td>
				<td>writer_info_basic.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>13</td>
				<td>财务中心</td>
				<td>&nbsp;</td>
				<td>information_account_finance.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>14</td>
				<td>充值记录</td>
				<td>anzhirecharge/findMyAnzhiRechargeAll.do</td>
				<td>information_account_recharge.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>15</td>
				<td>消费记录</td>
				<td>anzhiconsume/findAnzhiConsumeMySelf.do</td>
				<td>information_account_consume.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>16</td>
				<td>基本信息(作者)</td>
				<td>&nbsp;</td>
				<td>writer_info_basic.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>17</td>
				<td>资料修改(作者)</td>
				<td>anzhiauthor/updateAnzhiAuthor.do</td>
				<td>writer_info_update.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>18</td>
				<td>作品推荐</td>
				<td>anzhinovelrecommand/findAnzhiNovelRecommandMySelf.do</td>
				<td>writer_info_tui_jian.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>19</td>
				<td>我的书签</td>
				<td>anzhibookmark/findAnzhiBookmarkMySelf.do</td>
				<td>line_cave_bookmarks.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>20</td>
				<td>我的收藏</td>
				<td>anzhinovelmultifunction/findAnzhiNovelMultifunctionMyShoucang.do</td>
				<td>line_cave_collection.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>21</td>
				<td>我的评论</td>
				<td>anzhicomment/findMyAnzhiCommentAll.do</td>
				<td>my_comment_person.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>22</td>
				<td>我赞的书</td>
				<td>anzhinovelmultifunction/findAnzhiNovelMultifunctionMydianbook.do</td>
				<td>my_comment_prise.jsp</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>23</td>
				<td>我的回复</td>
				<td>anzhicomment/findMyAnzhiCommentreplyAll.do</td>
				<td>my_comment_reply.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>24</td>
				<td>收入概况</td>
				<td>anzhiconsume/findAnzhiConsumeMyCome.do</td>
				<td>line_myincome.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>25</td>
				<td>收入明细</td>
				<td>anzhiconsume/findAnzhiConsumeMyDetail.do</td>
				<td>line_myincome_detail.jsp</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>26</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>27</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>28</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>29</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>30</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>31</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>32</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>33</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>34</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>35</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>36</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>37</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>38</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>39</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>40</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>41</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>42</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>43</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>44</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>45</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>46</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr>
			  <tr>
				<td>47</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>48</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>49</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>50</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>郑娟</td>
			  </tr><tr>
				<td>51</td>
				<td>新建作品</td>
				<td>&nbsp;</td>
				<td>line_newproject.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>52</td>
				<td>管理作品</td>
				<td>findAnzhiNovelManage.do</td>
				<td>index/line_projectManage.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>53</td>
				<td>写新章节</td>
				<td>&nbsp;</td>
				<td>line_newchapter.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>54</td>
				<td>分卷管理</td>
				<td>anzhifenjuan/findAnzhiFenJuanAll.do</td>
				<td>line_bookmanage_roll.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>55</td>
				<td>修改分卷</td>
				<td>anzhichapter/findAnzhiChapterById.do</td>
				<td>line_newchapter.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>56</td>
				<td>订阅查询</td>
				<td>anzhichapter/dingyuechaxu.do</td>
				<td>line_bookmanage_ding.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>57</td>
				<td>修改作品</td>
				<td>anzhinovel/findAnzhiNovelById.do</td>
				<td>update_novel.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>58</td>
				<td>读者发消息</td>
				<td>&nbsp;</td>
				<td>my_news_send.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>59</td>
				<td>作家发送消息</td>
				<td>&nbsp;</td>
				<td>author_mail_send.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>60</td>
				<td>作家发件箱</td>
				<td>anzhimessage/findAnzhiMessageAll.do</td>
				<td>author_mail_send_all.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>61</td>
				<td>作家收件箱</td>
				<td>anzhimessage/findAnzhiMessageAll.do</td>
				<td>author_mail_receive</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>62</td>
				<td>读者收件箱</td>
				<td>anzhimessage/findAnzhiMessageAll.do</td>
				<td>my_news_receive.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>63</td>
				<td>读者发件箱</td>
				<td>anzhimessage/findAnzhiMessageAll.do</td>
				<td>my_news_send_all.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>64</td>
				<td>作家系统公告</td>
				<td>anzhinews/findAnzhiNewsAll.do</td>
				<td>system_public.jsp</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>65</td>
				<td>读者系统公告</td>
				<td>anzhinews/findAnzhiNewsAll.do</td>
				<td>my_news_system.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>66</td>
				<td>评论回复</td>
				<td>anzhicomment/commentAction.do</td>
				<td>replyComment</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>67</td>
				<td>全部评论</td>
				<td>anzhicomment/findMyAnzhiCommentAllIndex.do</td>
				<td>replyAllComment</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>68</td>
				<td>会员信息</td>
				<td>anzhimember/memberInfo.do</td>
				<td>memberInfo</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>69</td>
				<td>打赏界面</td>
				<td>anzhinovel/loadDaShangJsp.do</td>
				<td>da_shang_novlel</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>70</td>
				<td>购买章节</td>
				<td>anzhichapter/loadBuyChapter</td>
				<td>buy_chapter</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>71</td>
				<td>涉及安之币消费操作的</td>
				<td>打赏界面、购买章节、阅读界面</td>
				<td>AnzhiNovelRewardServiceImpl/cashDaShang、AnzhiChapterSubscribeServiceImpl/cashAnzhiChapterSubscribe,AnzhiChapterServiceImpl/cashRead,</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>72</td>
				<td>小说分类</td>
				<td>anzhinovel/recommand.do</td>
				<td>recommand</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>73</td>
				<td>书评管理</td>
				<td>&nbsp;</td>
				<td>line_book_discuss.jsp</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>74</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>75</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>76</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>77</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>78</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>79</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>80</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>81</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>82</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>83</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>84</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>85</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>86</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>87</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>88</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			  <tr>
				<td>89</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>90</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>91</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>92</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>93</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>94</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>95</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>96</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>97</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>98</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>99</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr><tr>
				<td>100</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>万勇波</td>
			  </tr>
			</table>

		</div>
  </body>
</html>
